#!/usr/bin/python

import os
import sys
import argparse
from PIL import Image

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
    
def is_clear(p):
	return p[0] + p[1] + p[2] + p[3] == 0

def process_png(path, filename, dest, border):
	absfile = os.path.join(path, filename)

	img = Image.open(absfile)
	pixels = img.load()
	
	w = img.size[0]
	h = img.size[1]
	
	left = w - 1
	right = 0
	top = h - 1
	bot = 0
	
	for y in range(h):
		for x in range(w):
			if not is_clear(pixels[x, y]):
				if y < top: top = y
				if y > bot: bot = y
				if x < left: left = x
				if x > right: right = x
	
	left = max(left - border, 0)
	top = max(top - border, 0)
	right = min(right + border, w - 1)
	bot = min(bot + border, h - 1)

	cropped = img.crop((left, top, right + 1, bot + 1))
	cropped.save(os.path.join(dest, filename), 'png')

	print("{0}: ({1},{2}) -> ({3},{4})".format(filename, left, top, right, bot))
	
	return {'left': left, 'top': top, 'right': right, 'bottom': bot }


def main(script, argv):
	parser = argparse.ArgumentParser(description='Trims transparent borders from PNGs.')
	parser.add_argument('src', help='input path to PNGs (directory or single file)', metavar='<src>')
	parser.add_argument('dest', help='path to output folder', metavar='<dest>')
	parser.add_argument('-m', '--meta', help='filename of meta file', required=True, metavar='<meta>', dest='meta')

	args = parser.parse_args()
	src = args.src
	dest = args.dest
	meta = args.meta

	meta_out = open(os.path.join(dest, meta), "w")

	if os.path.isfile(src):
		info = process_png(os.path.dirname(src), os.path.basename(src), dest, 1)
		meta_out.write("{0},{1},{2}\n".format(os.path.basename(src), info['left'], info['top']))
		
	else:
		files = [os.path.join(src, x) for x in os.listdir(src) if x.endswith(".png")]
		for i in os.listdir(src):
			if i.endswith(".png"):
				info = process_png(src, i, dest, 1)
				meta_out.write("{0},{1},{2}\n".format(i, info['left'], info['top']))
	
	meta_out.close()

if __name__ == '__main__':
    sys.exit(main(sys.argv[0], sys.argv[1:]))
